apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-management
  template:
    metadata:
      labels:
        app: device-management
    spec:
      containers:
      - name: device-management
        image: device-management:latest # Assumes local build or registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: SERVER_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: NAME_DB
          value: "device_db"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MQTT_HOST
          value: "mosquitto"
---
apiVersion: v1
kind: Service
metadata:
  name: device-management
spec:
  type: NodePort
  selector:
    app: device-management
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
