apiVersion: apps/v1
kind: Deployment
metadata:
  name: signing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signing
  template:
    metadata:
      labels:
        app: signing
    spec:
      containers:
      - name: signing
        image: signing:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SERVER_DB
          value: "postgres"
        - name: USER_DB
          value: "admin"
        - name: PASSWORD_DB
          value: "password"
        - name: NAME_DB
          value: "db_auth"
---
apiVersion: v1
kind: Service
metadata:
  name: signing
spec:
  type: NodePort
  selector:
    app: signing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
